// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nl.ica.ddoa.dda.routeplanner.domain;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import nl.ica.ddoa.dda.routeplanner.domain.Wegwerkzaamheid;
import nl.ica.ddoa.dda.routeplanner.domain.WegwerkzaamheidDataOnDemand;
import nl.ica.ddoa.dda.routeplanner.domain.WegwerkzaamheidIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect WegwerkzaamheidIntegrationTest_Roo_IntegrationTest {
    
    declare @type: WegwerkzaamheidIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: WegwerkzaamheidIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: WegwerkzaamheidIntegrationTest: @Transactional;
    
    @Autowired
    WegwerkzaamheidDataOnDemand WegwerkzaamheidIntegrationTest.dod;
    
    @Test
    public void WegwerkzaamheidIntegrationTest.testCountWegwerkzaamheids() {
        Assert.assertNotNull("Data on demand for 'Wegwerkzaamheid' failed to initialize correctly", dod.getRandomWegwerkzaamheid());
        long count = Wegwerkzaamheid.countWegwerkzaamheids();
        Assert.assertTrue("Counter for 'Wegwerkzaamheid' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void WegwerkzaamheidIntegrationTest.testFindWegwerkzaamheid() {
        Wegwerkzaamheid obj = dod.getRandomWegwerkzaamheid();
        Assert.assertNotNull("Data on demand for 'Wegwerkzaamheid' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Wegwerkzaamheid' failed to provide an identifier", id);
        obj = Wegwerkzaamheid.findWegwerkzaamheid(id);
        Assert.assertNotNull("Find method for 'Wegwerkzaamheid' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Wegwerkzaamheid' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void WegwerkzaamheidIntegrationTest.testFindAllWegwerkzaamheids() {
        Assert.assertNotNull("Data on demand for 'Wegwerkzaamheid' failed to initialize correctly", dod.getRandomWegwerkzaamheid());
        long count = Wegwerkzaamheid.countWegwerkzaamheids();
        Assert.assertTrue("Too expensive to perform a find all test for 'Wegwerkzaamheid', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Wegwerkzaamheid> result = Wegwerkzaamheid.findAllWegwerkzaamheids();
        Assert.assertNotNull("Find all method for 'Wegwerkzaamheid' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Wegwerkzaamheid' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void WegwerkzaamheidIntegrationTest.testFindWegwerkzaamheidEntries() {
        Assert.assertNotNull("Data on demand for 'Wegwerkzaamheid' failed to initialize correctly", dod.getRandomWegwerkzaamheid());
        long count = Wegwerkzaamheid.countWegwerkzaamheids();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Wegwerkzaamheid> result = Wegwerkzaamheid.findWegwerkzaamheidEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Wegwerkzaamheid' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Wegwerkzaamheid' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void WegwerkzaamheidIntegrationTest.testFlush() {
        Wegwerkzaamheid obj = dod.getRandomWegwerkzaamheid();
        Assert.assertNotNull("Data on demand for 'Wegwerkzaamheid' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Wegwerkzaamheid' failed to provide an identifier", id);
        obj = Wegwerkzaamheid.findWegwerkzaamheid(id);
        Assert.assertNotNull("Find method for 'Wegwerkzaamheid' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyWegwerkzaamheid(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Wegwerkzaamheid' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void WegwerkzaamheidIntegrationTest.testMergeUpdate() {
        Wegwerkzaamheid obj = dod.getRandomWegwerkzaamheid();
        Assert.assertNotNull("Data on demand for 'Wegwerkzaamheid' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Wegwerkzaamheid' failed to provide an identifier", id);
        obj = Wegwerkzaamheid.findWegwerkzaamheid(id);
        boolean modified =  dod.modifyWegwerkzaamheid(obj);
        Integer currentVersion = obj.getVersion();
        Wegwerkzaamheid merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Wegwerkzaamheid' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void WegwerkzaamheidIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Wegwerkzaamheid' failed to initialize correctly", dod.getRandomWegwerkzaamheid());
        Wegwerkzaamheid obj = dod.getNewTransientWegwerkzaamheid(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Wegwerkzaamheid' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Wegwerkzaamheid' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Wegwerkzaamheid' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void WegwerkzaamheidIntegrationTest.testRemove() {
        Wegwerkzaamheid obj = dod.getRandomWegwerkzaamheid();
        Assert.assertNotNull("Data on demand for 'Wegwerkzaamheid' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Wegwerkzaamheid' failed to provide an identifier", id);
        obj = Wegwerkzaamheid.findWegwerkzaamheid(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Wegwerkzaamheid' with identifier '" + id + "'", Wegwerkzaamheid.findWegwerkzaamheid(id));
    }
    
}
