// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nl.ica.ddoa.dda.routeplanner.domain;

import nl.ica.ddoa.dda.routeplanner.domain.Wegwerkzaamheid;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Wegwerkzaamheid_Roo_Configurable {
    
    declare @type: Wegwerkzaamheid: @Configurable;
    
}
